### ISSUE TITLE
Remove inline javascript to comply with some CSP

### ISSUE THREAD

**Issue by mossroy** [openzim/khan-chef#3]
Tested with https://download.kiwix.org/zim/videos/khan-academy-videos_ar_khws-l-dd_2021-12.zim

Every page has the following webp-polyfill related inline code : 

`<script>$(document).ready(function() { trigger_webp_polyfill(); });</script>`

**Comment by rgaudin** [comment]
Wrong repo ; Should be [kolibri2zim](https://github.com/openzim/kolibri2zim). FYI there is a [Scrapers list](https://github.com/openzim/overview/wiki/Scrapers-list)
